### ISSUE TITLE
sp.number_choice?

### ISSUE THREAD

**Issue by talesa** [awslabs/syne-tune#164]
Hello!
ST already has `sp.choice` for categorical variables, and `sp.finrange` and `sp.logfinrange` for numerical values, but  I feel that sometimes it is easier to manually specify the elements (as per `sp.choice`), but have them treated as numerical values by the GP-models and by the Blackbox-surrogate-models. Hence I'm wondering about implementing something like `sp.number_choice`, mostly for convenience, what do you think?

**Comment by mseeger** [comment]
choice already supports int and float entries, they do not have to be str.

But I'd really advice against using choice if any of the other types work. For model-based HPO, choice is 1-hot encoded, so the feature space is blown up. This is why I implemented finrange and logfinrange, because people seem to love these finite sets.

Honestly, I never saw HPO work worse with an infinite range than with a finite one.

**Comment by talesa** [comment]
>For model-based HPO, choice is 1-hot encoded, so the feature space is blown up. This is why I implemented finrange and logfinrange, because people seem to love these finite sets.

My motivation is exactly the same for which you implemented finrange and logfinrange.
`sp.number_choice` would be just another convenience function that I would like to use (and I guess other users will look for a feature like this too).

>choice already supports int and float entries, they do not have to be str.
Yes, I know, but even if we provide int or float, they will be 1-hot encoded for model-based HPO or Blackbox-surrogate-function modelling. 

Do you think that's a good enough motivation?
