### ISSUE TITLE
SageMaker Experiments compatibility

### ISSUE THREAD

**Issue by austinmw** [awslabs/syne-tune#206]
Hi, is this library compatible with [SageMaker Experiments](https://github.com/aws/sagemaker-experiments) tracking and/or SageMaker estimator `experiment_config`?

**Comment by mseeger** [comment]
Not right now, but we'd welcome a contribution which makes it so!

**Comment by geoalgo** [comment]
To add on this, SageMaker Experiments tracking works with with Syne Tune when running on SageMaker (you can use it when running either when using the SageMaker backend or if you use the remote launcher that launches tuning on SageMaker). 

The library does not use it to track its metadata though, mostly because tracking metadata offline is not supported in SageMaker Experiments (or was not when we looked at it).

**Comment by austinmw** [comment]
@geoalgo Thanks for your response. so if I create a SageMaker experiment, for example:
```python
experiment = Experiment.create(
    experiment_name='experiment-01',
    description='Classification task',
    sagemaker_boto_client=sm_client) 

```
How do I pass this experiment to the SagemakerBackend in order to be able to query trials with `sagemaker.analytics.ExperimentAnalytics`?

**Comment by geoalgo** [comment]
You can pass the `experiment_config` fit argument required to configure experiments in SageMaker estimator by setting the `sagemaker_fit_kwargs` parameter. For instance, something like:

```python
    trial_backend = SageMakerBackend(
        # we tune a PyTorch Framework from Sagemaker
        sm_estimator=PyTorch(
            entry_point="main.py",
            instance_type="ml.m5.large",
            instance_count=1,
            role=get_execution_role(),
            framework_version='1.7.1',
            py_version='py3',
        ),
        sagemaker_fit_kwargs={'experiment_config': your_experiment_config}
    )

```

**Comment by geoalgo** [comment]
I closed the issue, feel free to reopen if you have an issue with setting SageMaker experiment tracker.
