### ISSUE TITLE
Grid search in syne-tune

### ISSUE THREAD

**Issue by iaroslav-ai** [awslabs/syne-tune#265]
Hey folks,
would you be interested in grid search implemented in syne-tune? I had a few offline discussions with some of you already, and it seems that you are not against grid search added to syne-tune, but want to keep a record of that here. 

Additionally, would you have any pointers as to what would be the best way to add grid search to syne-tune?

**Comment by mseeger** [comment]
Hi Iaro, as I mentioned, the easiest way would be to use FIFOScheduler with random search and send in the grid via points_to_evaluate.

**Comment by aaronkl** [comment]
I agree that this would be the most straight-forward way to run grid search. However, it might be more accessible for non-expert syne tune users to have a simple baseline interface called GridSearch that wraps this functionality?

**Comment by mseeger** [comment]
Agree with Aaron, but this could simply wrap what I was suggesting, so we don't need to write redundant code.

**Comment by iaroslav-ai** [comment]
Thank you all for your inputs!!

**Comment by iaroslav-ai** [comment]
I will keep this open for any communication on addition of grid search to syne-tune.

**Comment by geoalgo** [comment]
> I agree that this would be the most straight-forward way to run grid search. However, it might be more accessible for non-expert syne tune users to have a simple baseline interface called GridSearch that wraps this functionality?

I agree with this point. The important part is probably to have a good way for the user to instantiate a grid-search. For instance, it could be something like:

```python
from syne_tune.optimizer.baselines import GridSearch
config_space = {
    "width": randint(0, 20),
    "height": randint(-100, 100),
}
scheduler = GridSearch(config_space, metric=metric, num_points=100)
```

We could also specify the list directly:

```python
from syne_tune.optimizer.baselines import GridSearch
scheduler = GridSearch(
  points_to_evaluate=[{"width": 0, "height": -100}, ...], 
  metric=metric, 
  num_points=100
)
```
however, this choice would make comparison with other schedulers harder (as they all take config_space as input) and also requires the user to split the grid manually. 

Given this, I think the best solution is to have the first option (config_space as input), we could also support an optional `points_to_evaluate` but having  both may be confusing.

**Comment by mseeger** [comment]
We could be even more ambitious and include some support for Latin Hypercube and/or Sobel sequences or pseudo-random stuff. If anybody knows some good code we could wrap?

**Comment by mseeger** [comment]
Actually, maybe it would be cleaner to implement this as a searcher.

**Comment by geoalgo** [comment]
> We could be even more ambitious and include some support for Latin Hypercube and/or Sobel sequences or pseudo-random stuff. If anybody knows some good code we could wrap?

scipy has great code for those (scipy.stats.qmc package). I tried sobol but did not get good results so I did not included it.

> Actually, maybe it would be cleaner to implement this as a searcher.

We can implement a searcher optionally but I think it will be important to have the method in baseline to have an easy entrypoint for a user (for the same reason as random-search, ASHA, BO, etc).

**Comment by duck105** [comment]
Hi everyone, 

I'm Jack and I will be working on the grid search implementation with Iaro.
So my initial thought about implementation will be:
1. Implement a new searcher call GridSearcher, which takes in a config_space as input, but the implementation would looks like the way that base searcher deal with points_to_evaluate. I might start with supporting only Categorical parameters. The points_to_evaluate would be an optional, but not recommended to use.
2. Modify the FIFOScheduler so that we could specify it to use the gird searcher.
3. Wrap the FIFOScheduler and GridSearcher to a new baseline class called GridSearch.

There's also a few details that might need to be decided, such as the way we enumerate all config combinations. I think we could let user to list numbers that is more promising first and try them first.

So that's my initial plan, any inputs, suggestions, comments are really helpful. Thank you.

**Comment by mseeger** [comment]
You can use HyperparameterRanges in order to obtain a grid for float or int hyperparameters. This encodes the range to [0, 1], optionally using a log transform. You can then use an equidistant grid in [0, 1], either including the boundaries 0, 1 or not, and map it back to the original space.

As for 2): This is just another value for the searcher argument, you need to then include it in the searcher factory.

**Comment by iaroslav-ai** [comment]
Hey folks, for our needs it is sufficient for grid search in syne-tune to work only with Categorical parameters; The user in principle can specify discrete values of continuous parameters via Categorical parameter. We would like to contribute GridSearch that supports Categorical parameters to begin with - but will implement it in a way that it is extensible to support equidistant splits (or some other way how to split hp values) for other parameter types as a future work. This way we are also more likely to meet our internal plans. Anyone have any concerns with this?

**Comment by geoalgo** [comment]
Hi Iaro, I would rather have grid-search for all hyperparameters at once rather than just categorical and then other types. This is because it is a relatively simple feature and I would be worried that it would look bad on us if grid-search is only supported on categorical (unless we commit it very quickly after but then I guess it makes sense to do both at once).

**Comment by iaroslav-ai** [comment]
I see. I would need to check with Jack on how much more complex this would be; Meanwhile - could you share any pointers on what you think getting discrete set of parameter values of a single continuous / int hp could look like? I see HyperparameterRange instances support from_ndarray method; Is this something we could use? Or is there some better way? Is `config_space` something that would always contain instances of HyperparameterRange?
