### ISSUE TITLE
Custom arguments packaging

### ISSUE THREAD

**Issue by martinferianc** [awslabs/syne-tune#273]
Dear creators, thank you for your great work. Is there a way how we could specify any packaging for the input hyperparameters for our main script? E.g. in our project we do not input hyperparameters directly as in `python3 train.py --width 1` but through `python3 train.py --hyperparameters='{"width": 1}'` to avoid adding a new argument to our parser and to avoid clutter each time we would like to change something. I have checked the FAQ but I have not found anything related. Thank you for your input!

**Comment by geoalgo** [comment]
Thanks for the kind words and for using Syne Tune! We do not support this at the moment, one reason we have currently this way of passing hyperparameters through command-line is that it then allows you to seamlessly run on AWS SageMaker.

That being said, we could support a mode for the `LocalBackend` (which I guess is the one you are using?) so that hyperparameters are rather written in a file `hyperparameters.json` so that your training script can directly load this file to not have to modify the parser. Would that be an option? (just to be clear, this would apply only for the local backend).

**Comment by martinferianc** [comment]
Dear @geoalgo, thank you for your prompt reply. Yes your proposed solution with the .json is a great compromise, it would be extremely helpful if this could be done.

**Comment by geoalgo** [comment]
I had a quick look, we already dump the hyperparameters as a file so this can be done already. 

I added an example in `nursery/` to show this can be done that we will merge soon (I put it in nursery given that I dont know how much people will have this use-case):

https://github.com/awslabs/syne-tune/blob/hyperparameters_file/benchmarking/nursery/tuning_with_hyperparameter_file/tuning_example.py

PS: in case you want to work directly with a python *function* and not a *script*, we also support this functionality, see this example for instance:

https://github.com/awslabs/syne-tune/blob/hyperparameters_file/examples/launch_height_python_backend.py

It is also an experimental feature given that we dont know yet how much people needs it but we are happy to get your feedback :-)

**Comment by martinferianc** [comment]
Thank you very much!
