### ISSUE TITLE
Custom results directory

### ISSUE THREAD

**Issue by martinferianc** [awslabs/syne-tune#275]
Dear creators, thank you again for your great work and perhaps sorry for being annoying with my suggestions/questions. Is it possible to change the home directory of different runs such that it is not `~/syne-tune` but a custom path? Thanks!

**Comment by martinferianc** [comment]
Sure that could work, ideally if it could be set as an attribute in the tuner that would be the best I guess. Thank you!

**Comment by geoalgo** [comment]
Ok thanks, we will work on this. The reason why I would prefer an environment variable is that there are many places where we access local files (launching tuning, getting experiments, downloading tabular datasets, ...) and it would probably be hard set them properly all at the same time.

**Comment by geoalgo** [comment]
Thanks for the idea! We added support for this, see for instance the description in FAQ:
https://github.com/awslabs/syne-tune/blob/main/docs/faq.md#-how-can-i-change-the-default-output-folder-where-tuning-results-are-stored

**Comment by ChongqiQu** [comment]
> Hi David,
> 
> ```
> export SYNETUNE_PATH="/home/martin/my-syne-tune-path/"
> python tuner.py
> ```
> Is this usage no longer valid?

**Comment by geoalgo** [comment]
Hi @ChongqiQu , apologies for the delay I was not available this week, I will take a look next week.

**Comment by geoalgo** [comment]
Hi @ChongqiQu , 

Using custom directory is still supported and is described in our FAQ

https://syne-tune.readthedocs.io/en/latest/faq.html#how-can-i-change-the-default-output-folder-where-tuning-results-are-stored
For instance, the following should work:
```bash
export SYNETUNE_FOLDER="~/new-syne-tune-folder"
python examples/launch_height_baselines.py
```

(the commands you are mentioning are just an illustration I gave to Martin)

**Comment by ChongqiQu** [comment]
Thank you for the clarification! I appreciate you pointing me to the FAQ.

I've retested it and it does work using these two usages.There may be some problems with my previous tests.

### Another implementation method of using custom directory

`tuner_path` can be set in `tuner.py` through the following code:
```
self.tuner_path = Path(experiment_path(tuner_name=self.name, local_path="~/new-syne-tune-folder"))
```
Here we can set `local_path` to get custom directory. But  There is no initialization attribute of `Class Tuner` . I hope `local_path` can be used as an initialization parameter that needs to be passed in 'Class Tuner'. So that we can set it arbitrarily in the tuner.

Just like this:
```
class Tuner:
    def __init__(
        self,
        trial_backend: TrialBackend,
        ... ,
        local_path: Optional[str] = None
    ):
   ...
   self.tuner_path = Path(experiment_path(tuner_name=self.name, local_path=local_path))
  ...
```
