### ISSUE TITLE
Unit tests in test_remote_launcher_path are commented out

### ISSUE THREAD

**Issue by ystein** [awslabs/syne-tune#729]
**Describe the bug**  

All tests in [test_remote_launcher_path](https://github.com/awslabs/syne-tune/blob/254ad0708703245e51da0b113f1067a2da92039a/tst/remote_launcher/test_remote_launcher_path.py) are commented out. Is this intended?

**To reproduce**  
1. Go to [test_remote_launcher_path](https://github.com/awslabs/syne-tune/blob/254ad0708703245e51da0b113f1067a2da92039a/tst/remote_launcher/test_remote_launcher_path.py) 

**Expected behavior**  
Unit tests are not commented out.

**Comment by mseeger** [comment]
Hello, good callout!

I suppose the tests are commented out (they should rather be marked to be skipped ...) because they use AWS. We run such tests as part of `integ-tests.yml` or `end-to-end-tests.yml`, but they should not be part of the unit test suite (which is supposed to run locally, without AWS, and each test is limited to a few secs).

**Comment by mseeger** [comment]
Path to solution:

- This code should not be a unit test
- It could be run as part of `integ-tests.yml` or `end-to-end-tests.yml`

**Comment by mseeger** [comment]
Closed by #810
