### ISSUE TITLE
INFO:root:Detected 2 GPUs on an EC2 m5d.12xlarge that has no GPU ?

### ISSUE THREAD

**Issue by la-cruche** [awslabs/syne-tune#85]
Hi,

I'm running Syne Tune on the `conda_python3` Jupyter kernel of a SageMaker-managed EC2 instance (ml.m5d.12xlarge notebook instance), that has no GPUs.
However, in the Syne Tune logs I see: 

`INFO:root:Detected 2 GPUs`

and then few lines below

```
DEBUG:root:Free GPUs: {0, 1}
DEBUG:root:Assigned GPU 0 to trial_id 0
```

But an m5d.12xlarge is not expected to have GPUs, right?

**Comment by mseeger** [comment]
Hi Olivier, are you using the local back-end here?

Note that if you use the sagemaker back-end, then every training job is run on a separate instance, which may well be a GPU-enabled one, even if the tuner runs on a CPU instance.

**Comment by geoalgo** [comment]
@mseeger this logging only happens with the local-backend

@la-cruche thanks for reporting this, we will take a look and fix it soon. Note that this wont have any effective impact if you run on a machine with no GPU since it will just instantiate the environment variable CUDA_VISIBLE_DEVICE before calling your script.

**Comment by la-cruche** [comment]
@mseeger local backend

**Comment by geoalgo** [comment]
Hi Olivier, I was not able to reproduce this issue. Could you share a minimal example to reproduce the error if you see it again?
